let D;const $=s=>document.querySelector(s),app=$('#app');
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const T=id=>D.tools.find(t=>t.id===id),C=id=>D.categories.find(c=>c.id===id);
const inCat=(t,c)=>t.category===c||(t.also||[]).includes(c);
const li=a=>'<ul>'+a.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>';
const ol=a=>'<ol>'+a.map(x=>`<li>${esc(x)}</li>`).join('')+'</ol>';
const card=t=>`<article class="card"><div class="row"><span class="ic">${t.icon}</span><div><h3>${esc(t.name)}</h3><small>${esc(C(t.category).name)}</small></div><b>★ ${t.rating}</b></div><p>${esc(t.description)}</p><p class="tags"><span>${t.freePlan?'خطة مجانية':'بدون خطة مجانية'}</span><span>${t.difficulty}</span></p><p><small>أفضل استخدام: ${esc(t.bestFor)}</small></p><div class="row"><a class="btn" href="#/tool/${t.id}">تعلم استخدامها</a><a class="btn ghost" href="${t.website}" target="_blank" rel="noopener">زيارة الأداة</a></div></article>`;
const grid=a=>a.length?`<div class="grid">${a.map(card).join('')}</div>`:'<p class="mu">لا توجد أدوات بعد. أضف أداة في data/tools.json.</p>';
const sec=(h,a)=>`<h2>${h}</h2>${grid(a)}`;
const catCard=c=>`<a class="card cat" href="#/category/${c.id}"><span class="ic">${c.icon}</span>${esc(c.name)}</a>`;
const norm=s=>s.toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/[ًٌٍَُِّْ]/g,'');
const STOP=['اريد','ابي','ابغي','صناعه','انشاء','عمل','كيف','ماذا','علي','عن','في','من','الي'];
function search(q){const w=norm(q).split(/\s+/).map(x=>x.replace(/^ال/,'')).filter(x=>x.length>1&&!STOP.includes(x));if(!w.length)return[];
return D.tools.map(t=>{const h=norm([t.name,t.description,t.tags,t.bestFor,C(t.category).name,...(t.also||[]).map(c=>C(c).name)].join(' '));return[t,w.filter(x=>h.includes(x)).length]}).filter(x=>x[1]).sort((a,b)=>b[1]-a[1]||b[0].rating-a[0].rating).map(x=>x[0])}
const top=a=>[...a].sort((x,y)=>y.rating-x.rating);
const views={
home(){return`<section class="hero"><h1>دليلك إلى عالم الذكاء الاصطناعي</h1><p>اكتشف أفضل أدوات الذكاء الاصطناعي لكل مجال وتعلم كيفية استخدامها خطوة بخطوة.</p><input id="q" class="search" placeholder="ابحث: أريد صناعة فيديو، برمجة، ترجمة…" autocomplete="off"><p><a class="btn" href="#/tools">استكشف الأدوات</a> <a class="btn ghost" href="#/learn">تعلم من البداية</a></p></section><div class="wrap"><div id="res"></div><div id="main"><h2>المجالات الأكثر شعبية</h2><div class="grid">${D.categories.slice(0,8).map(catCard).join('')}</div>${sec('⭐ أدوات مميزة',top(D.tools).slice(0,3))}${sec('🆕 أحدث المضافة',D.tools.slice(-3).reverse())}${sec('🆓 مجانية',D.tools.filter(t=>t.freePlan).slice(0,3))}${sec('🌱 مناسبة للمبتدئين',D.tools.filter(t=>t.difficulty=='مبتدئ').slice(0,3))}</div></div>`},
tools(){return`<div class="wrap"><h1>جميع الأدوات</h1><div class="pick"><button class="btn ghost" data-f="all">الكل</button><button class="btn ghost" data-f="free">مجانية</button><button class="btn ghost" data-f="beg">للمبتدئين</button></div><div id="list">${grid(top(D.tools))}</div></div>`},
categories(){return`<div class="wrap"><h1>المجالات</h1><div class="grid">${D.categories.map(catCard).join('')}</div></div>`},
category(id){const c=C(id);if(!c)return views.categories();const a=top(D.tools.filter(t=>inCat(t,id))),f=(x,n)=>x?`<div class="box"><b>${n}:</b> ${esc(x.name)}</div>`:'';
return`<div class="wrap"><h1>${c.icon} أفضل أدوات ${esc(c.name)}</h1><p class="mu">${esc(c.desc)}</p>${f(a.find(t=>t.difficulty=='مبتدئ'),'أفضل أداة للمبتدئين')}${f(a.find(t=>t.freePlan),'أفضل أداة مجانية')}${f(a.find(t=>t.difficulty!='مبتدئ')||a[0],'أفضل أداة احترافية')}<h2>ترتيب الأدوات</h2>${grid(a)}${a.length>1?`<p><a class="btn" href="#/compare/${a.slice(0,3).map(t=>t.id).join(',')}">قارن هذه الأدوات</a></p>`:''}</div>`},
tool(id){const t=T(id);if(!t)return views.tools();document.title=t.name+' | AI Guide';
return`<div class="wrap"><h1>${t.icon} ${esc(t.name)}</h1><p>${esc(t.description)}</p><p class="tags"><span>${t.pricing}</span><span>${t.difficulty}</span><span>★ ${t.rating}</span></p><div class="box"><h3>ماذا تستطيع أن تفعل؟</h3>${li(t.features)}</div><div class="box"><h3>أفضل الاستخدامات</h3><p>${esc(t.bestFor)}</p></div><div class="grid"><div class="box"><h3>المميزات</h3>${li(t.pros)}</div><div class="box"><h3>العيوب</h3>${li(t.cons)}</div></div><div class="box"><h3>خطوات البدء</h3>${ol(t.tutorials)}</div><div class="box"><h3>Prompts جاهزة</h3>${t.prompts.map(p=>`<pre>${esc(p)}</pre>`).join('')}<small>نصيحة: أضف السياق والجمهور والشكل المطلوب لنتائج أفضل.</small></div>${t.alternatives.length?sec('الأدوات البديلة',t.alternatives.map(T).filter(Boolean)):''}<p><a class="btn" href="${t.website}" target="_blank" rel="noopener">الموقع الرسمي</a></p></div>`},
compare(ids){const sel=(ids||'').split(',').filter(T);return`<div class="wrap"><h1>مقارنة أدوات الذكاء الاصطناعي</h1><div class="pick">${D.tools.map(t=>`<label class="btn ghost"><input type="checkbox" value="${t.id}" ${sel.includes(t.id)?'checked':''}> ${esc(t.name)}</label>`).join('')}</div><div id="cmp"></div></div>`},
learn(){return`<div class="wrap"><h1>تعلم الذكاء الاصطناعي</h1><div class="grid">${D.lessons.map(l=>`<a class="card" href="#/lesson/${l.id}"><b>المستوى ${l.level}</b><h3>${esc(l.title)}</h3></a>`).join('')}</div></div>`},
lesson(id){const l=D.lessons.find(x=>x.id==id);if(!l)return views.learn();return`<div class="wrap"><small>المستوى ${l.level}</small><h1>${esc(l.title)}</h1><div class="box"><h3>الشرح</h3><p>${esc(l.text)}</p></div><div class="box"><h3>مثال</h3><p>${esc(l.example)}</p></div><div class="box"><h3>خطوات عملية</h3>${ol(l.steps)}</div><div class="box"><h3>Prompt جاهز</h3><pre>${esc(l.prompt)}</pre></div><div class="box"><h3>تمرين</h3><p>${esc(l.exercise)}</p></div><a class="btn ghost" href="#/learn">كل الدروس</a></div>`},
wizard(c){return`<div class="wrap"><h1>ماذا تريد أن تفعل؟</h1><div class="pick">${D.wizard.map(w=>`<a class="btn ${w.cat==c?'':'ghost'}" href="#/wizard/${w.cat}">${esc(w.label)}</a>`).join('')}</div>${c?sec('الأدوات المقترحة',top(D.tools.filter(t=>inCat(t,c))).slice(0,3)):''}</div>`},
about(){return`<div class="wrap"><h1>About</h1><p>AI Guide دليل عربي لأدوات الذكاء الاصطناعي. البيانات في ملف JSON وتتغير الأسعار والخطط، فتحقق من الموقع الرسمي لكل أداة.</p></div>`},
contact(){return`<div class="wrap"><h1>Contact</h1><p>للاقتراحات أو إضافة أدوات: <a href="mailto:${esc(D.site.email)}"><b>${esc(D.site.email)}</b></a></p></div>`}};
function bind(){const q=$('#q');if(q)q.oninput=()=>{const r=search(q.value);$('#main').hidden=!!q.value;$('#res').innerHTML=q.value?(r.length?'<h2>نتائج البحث</h2>'+grid(r):'<p>لا نتائج.</p>'):''};
document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{const f=b.dataset.f;$('#list').innerHTML=grid(top(D.tools).filter(t=>f=='free'?t.freePlan:f=='beg'?t.difficulty=='مبتدئ':1))});
const cb=$('#cmp')&&document.querySelectorAll('input[type=checkbox]');if(cb){const go=()=>{const s=[...cb].filter(x=>x.checked).map(x=>T(x.value));$('#cmp').innerHTML=s.length<2?'<p class="mu">اختر أداتين أو أكثر.</p>':'<table><tr><th></th>'+s.map(t=>`<th>${esc(t.name)}</th>`).join('')+'</tr>'+[['السعر',t=>t.pricing],['الخطة المجانية',t=>t.freePlan?'نعم':'لا'],['المستوى',t=>t.difficulty],['التقييم',t=>'★ '+t.rating],['المميزات',t=>t.features.join('، ')],['أفضل استخدام',t=>t.bestFor]].map(r=>`<tr><th>${r[0]}</th>${s.map(t=>`<td>${esc(r[1](t))}</td>`).join('')}</tr>`).join('')+'</table>'};cb.forEach(x=>x.onchange=go);go()}}
function route(){const[,v='home',a]=location.hash.slice(1).split('/');document.title='AI Guide | دليلك إلى عالم الذكاء الاصطناعي';app.innerHTML=(views[v||'home']||views.home)(a);bind();scrollTo(0,0)}
const th=document.documentElement;try{th.dataset.theme=localStorage.getItem('t')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light')}catch(e){th.dataset.theme='light'}
$('#theme').onclick=()=>{th.dataset.theme=th.dataset.theme=='dark'?'light':'dark';try{localStorage.setItem('t',th.dataset.theme)}catch(e){}};
fetch('data/tools.json').then(r=>r.json()).then(d=>{D=d;route();addEventListener('hashchange',route)}).catch(()=>app.innerHTML='<p class="wrap">تعذر تحميل البيانات. شغّل الموقع عبر خادم محلي أو GitHub Pages.</p>');
